### ISSUE TITLE
Get people involved

### ISSUE THREAD

**Issue by indus** [js-org/learn.js.org#2]
@daniellmb any ideas? Should I post on Twitter? But maybe you have a better network and reputiton

**Comment by daniellmb** [comment]
I'll send out an call for contributors today

**Comment by indus** [comment]
I have invited @glombek to the team of editors. Should´t we leave this open for people to ask for invitations. Or should we ask and hand-pick them (maybe after a commit)

**Comment by daniellmb** [comment]
I'd rather hand pick based on thier interest and contributions to the project. I created a team on slack (https://jsorg.slack.com). Send me your email at dlamb.open.source@gmail.com and I'll send you an invite.

**Comment by daniellmb** [comment]
@indus do you think https://jsorg.slack.com is a good fit for team communication? I perfer it, but we could do an [IRC channel](http://webchat.freenode.net/?channels=jsorg) or use https://gitter.im.

**Comment by daniellmb** [comment]
I was thinking more for planning and administrative things like issue prioritisation, task-to-milestone allocation, voting on moderators, etc. I am all for transparency, but it can be challenging to have a frank conversation if every comment is under public scrutiny. If you feel having a team forum is not needed yet that is fine with me.
