### ISSUE TITLE
Grant Access for Classroom for GitHub?

### ISSUE THREAD

**Issue by indus** [js-org/learn.js.org#8]
@daniellmb
I got an email with a notification to Grant Access to the JS.ORG organisation to Classroom for GitHub.

Are you still working on learn.js.org?
I don't want to grant access to the org but only the learn.js.org repo. Is that an option?

**Comment by daniellmb** [comment]
Yeah I have been playing with the format for a while. Trying to come up with something that will work well. From a maint and collaboration standpoint. I think it's at the org level not project. If you don't want to use classroom that's fine, I was just checking it out, probably won't use it for learn.js.
