### ISSUE TITLE
Closing

### ISSUE THREAD

**Issue by indus** [js-org/learn.js.org#9]
I think I´m going to close this...

**Comment by daniellmb** [comment]
:frowning: I haven't had much time to put into this project, but I still this it could be an _amazing_ resource. I am especially excited about how the curriculum has a radically unique pedagogy. In that it teaches just enough to get you started, then based on how you want to write JavaScript, dives deeper into the language structures and techniques that apply. For example, if you prefer a functional programming style you're taught about recursion and promises versus loops and callbacks.

How much of the [proposed curriculum](https://github.com/js-org/learn.js.org/wiki/Curriculum-Outline) do you need implemented to keep the project alive? :smile:

**Comment by indus** [comment]
I just thought nobody is interested anymore. When I see FreeCodeCamp I - for myself - am not very motivated to invest time. But I can keep this alive of you want...

**Comment by daniellmb** [comment]
There is a lot of good information at FreeCodeCamp, but I don't agree with how it is organized. The overall groupings are huge with no logical breakdown of the concepts.

Newcomers can feel overwhelmed with no step-by-step path to help guide them. Basically, all you get is a huge list of headings that link to demo code. That's ok for teaching the mechanics of *how* something can be done, but does not effectively tell you *the why* in a cohesive manner.

In my opinion, they have relied much too heavily on the coding challenges, then try to make up for it with a chat window to get help.

I also have ideas for a much better way that collaborators can contribute and refine the curriculum.

**Comment by tiborsaas** [comment]
I've just shared your project in a popular facebook frontend group :) If it requires little time you could leave it running a bit more. Maybe a web service to set up the DNS might be a good idea.

**Comment by indus** [comment]
What DNS are you talking about?

**Comment by indus** [comment]
Closing this issue and the repo...
